version: '2.1'

services:

  postgres12:
    image: postgres:12-bullseye
    restart: always
    container_name: postgres12
    volumes:
      - /home/vladimir/postgre12:/var/lib/postgresql/data:rw
      - /home/vladimir/backup:/var/lib/postgresql/backup:rw
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres

  postgres12-bak:
    image: postgres:12-bullseye
    restart: always
    container_name: postgres12-bak
    volumes:
      - /home/vladimir/backup:/var/lib/postgresql/backup:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres